version: 2
jobs:
  test:
    docker:
      - image: node:16-buster
    steps:
      - checkout
      - run:
          command: npm install --legacy-peer-deps
      - run:
          name: Run tests
          command: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
