version: 2.1
executors:
  node-executor:
    docker:
      - image: node:16-buster
jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - run: npm install --legacy-peer-deps
      - run:
          name: Run tests
          command: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
