import '@/globals.css';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { VercelToolbar } from '@vercel/toolbar/next';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import { ClerkProvider } from '@clerk/nextjs';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Spot',
  description: 'Generated by create next app',
};

export default async function RootLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const shouldInjectToolbar = process.env.NODE_ENV === 'development';
  return (
    <html lang='en'>
      {/* suppressHydrationWarning: Fix hydration warning caused by some chrome extensions, only affects body, not children */}
      <ClerkProvider>
        <body
          className={`${inter.className} inset-0`}
          suppressHydrationWarning
        >
          {children}
          {shouldInjectToolbar && <VercelToolbar />}
          <SpeedInsights />
        </body>
      </ClerkProvider>
    </html>
  );
}
